steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/angular-vector-456406-i8/myapp:latest',
      '.'
    ]

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/angular-vector-456406-i8/myapp:latest'
    ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      'extractor-service',  # Your service name
      '--image=gcr.io/angular-vector-456406-i8/myapp:latest',
      '--region=asia-south1',
      '--platform=managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/angular-vector-456406-i8/myapp:latest'

options:
  logging: CLOUD_LOGGING_ONLY
